apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-application-set
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: default-cluster
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-application-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: demo-namespace
        server: "{{server}}"
      project: demo-app-project
      sources:
        - path: ./
          repoURL: https://github.com/fwalker-redhat/gitops-demo.git
          targetRevision: main
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true